In [194]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB

In [195]:
import numpy as np

In [196]:
from sklearn import linear_model

In [197]:
from ipykernel import kernelapp as app

In [198]:
from sklearn.feature_selection import SelectFromModel

In [199]:
import pandas as pd

In [200]:
vectorizer = CountVectorizer()

In [201]:
vectorizerTest = CountVectorizer()

In [202]:
tfidf_transformer = TfidfTransformer()

In [203]:
f = open("train_tweets_preprocessed.txt","r", encoding="utf8")

In [204]:
t = open("test_tweets_preprocessed.txt","r", encoding="utf8")

In [205]:
mySentenceList = []
myScoreList = []

In [206]:
myTestSentenceList = []
myTestScoreList = []

In [207]:
for line in f:
    line =line.strip()
    splittedLine = line.split(" ")
    score = splittedLine[len(splittedLine)-1]
    myScoreList.append((float(score.strip())+1)/2)
    del splittedLine[len(splittedLine)-1]
    sentence =" ".join(splittedLine)
    mySentenceList.append(sentence)

In [208]:
for line in t:
    line =line.strip()
    splittedLine = line.split(" ")
    score = splittedLine[len(splittedLine)-1]
    print(score.strip())
    myTestScoreList.append((float(score.strip())+1)/2)
    del splittedLine[len(splittedLine)-1]
    sentence =" ".join(splittedLine)
    myTestSentenceList.append(sentence)

-1
1
0
0
-1
-0.2
0
-0.3
0
1
1
-0.5
-0.4
0
0
0
-1
-0.2
0
0.1
-1
0
-1
-1
0
-0.6
0
0
-0.6
-0.7
-1
1
-0.7
-1
-1
0
0
0
0
-1
0
0
-0.3
0.7
0
-0.7
0
0
-0.4
-1
-1
-1
0
0
1
1
0
0
1
0
-0.8
-0.4
0
0
-1
-0.8
-1
-1
-1
-1
-1
-1
0.6
0.4
0
-0.5
-0.8
-0.1
0.2
-0.1
0.1
-0.2
-0.2
-0.2
-0.4
-0.1
-0.1
-0.5
-0.3
0.1
-0.4
0.1
-0.3
-0.2
-0.1
0.2
1
0.3
-0.2
-0.1
-0.2
0
0
-0.5
0
0
-0.1
-0.5
-0.4
-0.1
-0.4
-0.4
-0.3
0
-0.4
-0.8
-0.5
-0.5
-0.7
-0.2
-0.1
-0.4
-0.2
-0.1
-0.2
0.3
-0.3
-0.2
-0.2
-0.5
-0.1
0.8
-0.5
0
-0.3
-0.1
-0.1
-0.7
0
-0.5
-0.2
0.4
-0.2
-0.6
-0.5
-0.5
-0.2
0.9
-0.7
0
-0.8
0
-0.2
0.4
0.1
-0.7
-0.6
-0.5
-0.1
0
-0.2
-0.1
-0.1
-0.6
-1
0.7
0.4
-0.6
-0.7
-0.8
-0.1
-0.1
-0.4
-0.7
0
0
-0.5
-0.7
0
0
-0.3
1
0.3
0
-0.3
-0.6
-0.7
0
0
-0.5
0.3
-1
-1
0.4
0
0
0
-0.2
0.2
1
-1
1
0
0
-1
-0.2
0
-0.3
0
1
1
-0.5
-0.4
0
0
0
-1
-0.2
0
0.1
-1
0
-1
-1
0
-0.6
0
0
-0.6
-0.7
-1
1
-0.7
-1
-1
0
0
0
0
-1
0
0
-0.3
0.7
0
-0.7
0
0
-0.4
-1
-1
-1
0
0
1
1
0
0
1
0
-0.8
-0.4
0
0
-1
-0.8
-1
-1
-1
-1
-1
-1
0.6
0.4
0
-0.5
-0.8
-0.1
0.2
-0.

In [209]:
mySentenceList

['Gü herhangi saat uygun olmak teşekkür etmek',
 'sormak yok , sadece belirtmek istemek şikâyet , kimse rahat etmek istemek . . duyarlı teşekkür . .',
 'merhaba , platform üzerinde , güncellemek ağır çalışmak başlamak . bilgi dâhil mi QuestionMark',
 'hesap ilgi basit Ko hakkında alo garanti zor sistem görmek QuestionMark QuestionMark',
 '38631234 numara şikâyet dönüşmek gerçek QuestionMark',
 'maaş . 300-500 Tl para . Varmı',
 'Http .',
 'dosya masraf geri al . çekinmek',
 'dosya masraf geri Http .',
 'dosya masraf geri almak istemek duyurmak , Mahke karmak ek . dosya masraf geri al Http .',
 '05384173149 iletişim',
 'teşekkür etmek',
 'teşekkür ilgi ExclamationMark ExclamationMark',
 'banka istek dış ilişki bugün itibarî başlamak . mutsuz Ko hakkında şimdilik konuşmak istemek .',
 'ilgi acil aramak mı QuestionMark 2125963492',
 'sayın garanti arkadaş bugün resmî tatil sanmak . hâlen aramak sormak yok . hayır',
 'geçmek kardeş be iletişim 3 günde 8 ker aranmak insan',
 'müşteri mağdur

In [210]:
myScoreList

[0.6,
 0.25,
 0.45,
 0.2,
 0.35,
 0.5,
 0.5,
 0.25,
 0.35,
 0.35,
 0.5,
 0.65,
 0.3,
 0.15000000000000002,
 0.5,
 0.3,
 0.15000000000000002,
 0.0,
 0.09999999999999998,
 0.3,
 0.25,
 0.25,
 0.65,
 0.0,
 0.35,
 0.0,
 0.4,
 1.0,
 0.35,
 0.4,
 0.35,
 0.5,
 0.5,
 0.35,
 0.4,
 0.2,
 1.0,
 0.35,
 0.5,
 1.0,
 0.35,
 0.45,
 0.35,
 0.0,
 0.5,
 0.15000000000000002,
 0.35,
 0.75,
 0.35,
 0.0,
 0.5,
 0.25,
 0.5,
 0.35,
 1.0,
 0.4,
 0.35,
 0.4,
 0.0,
 0.0,
 0.35,
 0.0,
 0.5,
 0.0,
 0.0,
 0.09999999999999998,
 0.6,
 0.04999999999999999,
 0.5,
 0.5,
 0.5,
 0.25,
 0.5,
 0.65,
 0.5,
 1.0,
 0.85,
 0.5,
 0.9,
 1.0,
 0.65,
 0.5,
 0.2,
 0.6,
 0.5,
 0.35,
 0.5,
 0.5,
 0.5,
 1.0,
 0.0,
 0.85,
 0.0,
 0.5,
 0.15000000000000002,
 1.0,
 0.4,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.5,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.5,
 0.0,
 0.85,
 0.5,
 1.0,
 0.2,
 0.15000000000000002,
 0.5,
 0.0,
 0.0,
 0.0,
 0.2,
 0.75,
 0.5,
 0.5,
 0.35,
 0.0,
 0.0,
 0.0,
 0.15000000000000002,
 0.25,
 0.0,
 0.0,

In [211]:
y = np.array(myScoreList)

In [212]:
yTest = np.array(myTestScoreList)

In [213]:
y = y.reshape(-1)

In [214]:
yTest = yTest.reshape(-1)

In [215]:
y=y.astype('float')

In [216]:
yTest=yTest.astype('float')

In [217]:
y.dtype

dtype('float64')

In [218]:
yTest.dtype

dtype('float64')

In [219]:
data_corpus = mySentenceList

In [220]:
test_data_corpus = myTestSentenceList

In [221]:
X = vectorizer.fit_transform(data_corpus)

In [222]:
XTest = vectorizer.transform(test_data_corpus)

In [223]:
print(XTest.toarray())

[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]


In [224]:
print(vectorizer.get_feature_names())


['00', '000', '01', '015', '018471807', '02', '0212', '028', '03', '05', '05058317484', '05063090319', '05327704050', '0535', '05384173149', '05388880125', '05397965555', '0545', '05456103535', '08', '09', '10', '100', '1001122869331', '11', '115', '12', '120', '13', '1309', '14', '1415', '15', '16', '17', '175', '18', '19', '20', '2000', '2004', '2009', '2013', '2014', '2123181818', '2125963492', '23', '24', '25', '2986', '30', '300', '333', '334', '34', '36', '38631234', '41', '410', '43', '444', '4440333', '45', '46', '50', '500', '5000', '507', '5127', '532', '5356379720', '55', '576', '58', '60', '6103055', '619', '630', '640', '65', '656', '68', '686883', '69', '694', '70', '71', '73', '77', '787', '94', 'abdullah', 'abi', 'about', 'acil', 'acilen', 'aciz', 'acımak', 'ad', 'ada', 'adet', 'adres', 'adına', 'afedersin', 'aidat', 'ak', 'akbank', 'akbaş', 'akrep', 'aksi', 'aksu', 'aktarmak', 'aktif', 'akıllı', 'akşam', 'al', 'ala', 'alaka', 'alaçam', 'alkışlamak', 'allah', 'almak', '

In [225]:
X.shape

(757, 1304)

In [226]:
XTest.shape

(400, 1304)

In [227]:
X_train_tfidf = tfidf_transformer.fit_transform(X)

In [228]:
X_train_tfidf.shape

(757, 1304)

In [229]:
#clf = MultinomialNB().fit(X_train_tfidf, y)

In [230]:
reg = linear_model.BayesianRidge()

In [231]:
 XArray = X.toarray()

In [232]:
XTestArray = XTest.toarray()

In [233]:
reg.fit(XArray, y)

BayesianRidge(alpha_1=1e-06, alpha_2=1e-06, compute_score=False, copy_X=True,
       fit_intercept=True, lambda_1=1e-06, lambda_2=1e-06, n_iter=300,
       normalize=False, tol=0.001, verbose=False)

In [234]:
reg.predict (XTestArray[0])

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 0.31560523])

In [235]:
print('Regression score: '
      + str(reg.score(XTestArray, yTest)))

Regression score: 0.117477844719


In [93]:
predicted = reg.predict(XTestArray)


In [94]:
model = SelectFromModel(reg, prefit=True, threshold=0.05)

In [95]:
X_new = model.transform(XArray)

In [96]:
X_new.shape

(757, 102)

In [97]:
XArray.shape

(757, 1304)

In [98]:
XTest_new = model.transform(XTestArray)

In [99]:
reg2 = linear_model.BayesianRidge(compute_score=True)

In [100]:
reg2.fit(X_new,y)

BayesianRidge(alpha_1=1e-06, alpha_2=1e-06, compute_score=True, copy_X=True,
       fit_intercept=True, lambda_1=1e-06, lambda_2=1e-06, n_iter=300,
       normalize=False, tol=0.001, verbose=False)

In [104]:
reg.fit(X_new, y)

BayesianRidge(alpha_1=1e-06, alpha_2=1e-06, compute_score=False, copy_X=True,
       fit_intercept=True, lambda_1=1e-06, lambda_2=1e-06, n_iter=300,
       normalize=False, tol=0.001, verbose=False)

In [101]:
reg2.predict(XTest_new[0])

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 0.31165451])

In [102]:
XTest_new.shape

(400, 102)

In [105]:
reg.predict (XTest_new[0])

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 0.31165451])

In [135]:
a = reg.coef_

In [141]:
a.argmax()

1072

In [139]:
b = a.tolist()

In [147]:
for i in range(len(b)):
    if b[i]>= 0.1:
        print(str(i)+"poz")
    elif b[i]<= -0.1:
        print(str(i)+"neg")

204neg
275poz
898poz
1072poz
1294neg


In [153]:
vectorizer.get_feature_names()[275]

'bonus'

In [192]:
file = open("train21features.txt","r", encoding="utf8")

In [193]:
trainScore= []
trainFeatures=[]

In [ ]:
for line in file:
    line =line.strip()
    splittedLine = line.split(" ")
    score = splittedLine[len(splittedLine)-1]
    trainScore.append((float(score.strip())+1)/2)
    del splittedLine[len(splittedLine)-1]
    sentence =" ".join(splittedLine)
    trainFeatures.append(sentence)